---
- name: Install i3-gaps
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - i3-gaps
    - i3lock
    - i3status

- name: Install i3 extras
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - conky
    - dmenu
    - dunst
    - feh
    - polybar
    - redshift
    - rxvt-unicode
    - scrot
    - terminus-font
    - ttf-dejavu
    - udiskie
    - urxvt-perls
    - xcalib
    - xf86-input-synaptics
    - xorg-xmodmap
    - xorg-xrdb
