---
- name: Install i3
  become: true
  community.general.pacman:
    name:
      - i3
      - i3lock
      - i3status
    update_cache: true
  tags: [ 'i3' ]

- name: Install i3 extras
  become: true
  community.general.pacman:
    name:
      - conky
      - dmenu
      - dunst
      - feh
      - scrot
      - xcalib
      - xf86-input-synaptics
      - xorg-xmodmap
      - xorg-xrdb
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
  tags: [ 'i3' ]
