---
- name: Update cache and install dependencies
  package:
    name: dirmngr
    update_cache: yes

- name: Install Regolith ppa
  apt_repository:
    repo: ppa:regolith-linux/release
    state: present

- name: Install i3-gaps
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - i3-gaps
    - i3lock
    - i3status

- name: Install i3 extras
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - conky
    - dmenu
    - dunst
    - feh
    - redshift
    - rxvt-unicode
    - scrot
    - ttf-dejavu
    - udiskie
    - xcalib
