---
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Create ~/.config/i3 directory
  become: false
  file:
    path: "~/.config/i3"
    state: directory
  tags: [ 'i3' ]

- name: generate i3 config files
  become: false
  template:
    src: "{{ item }}.j2"
    dest: "~/.config/i3/{{ item }}"
  with_items:
    - Xresources.dark
    - Xresources.light
    - config
    - conkyrc
    - dark.xresources
    - dunstrc
    - gtk-3.0-settings
    - gtkrc-2.0
    - light.xresources
    - xinitrc
    - xmodmap
    - xresources
  tags: [ 'i3' ]

- name: symlink xinitrc
  become: false
  file:
    src: "~/.config/i3/xinitrc"
    dest: "~/.xinitrc"
    state: link
  tags: [ 'i3' ]

- name: create $HOME/screenshots dir for scrot
  become: false
  file:
    path: "~/screenshots/"
    state: directory
  tags: [ 'i3' ]

- name: Set default background image for feh
  become: false
  copy:
    src: background.jpg
    dest: "~/.config/i3/background.jpg"
